"""update user

Revision ID: 80ab8c662764
Revises: 3da85c9a7ac1
Create Date: 2025-05-11 20:45:21.358629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ab8c662764'
down_revision: Union[str, None] = '3da85c9a7ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('captcha_passed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('referals_count', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'referals_count')
    op.drop_column('users', 'captcha_passed')
    # ### end Alembic commands ###
