"""new user column

Revision ID: a220b8b73d6b
Revises: 93fa21c3e1ee
Create Date: 2025-05-12 19:52:35.095007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a220b8b73d6b'
down_revision: Union[str, None] = '93fa21c3e1ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blocked', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint('users_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_referals_count'), 'users', ['referals_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referals_count'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_id_key', 'users', ['id'])
    op.drop_column('users', 'blocked')
    # ### end Alembic commands ###
